import Head from 'next/head'
import Navigation from '../components/Navigation.js'
import OutlinedArrow from '../components/OutlinedArrowSVG.js'
import styles from '../styles/Home.module.css'
import StatusText from '../components/StatusText.js'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Simon Wilmots {"\u{1F680}"}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/img/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <Navigation hideHomeButton/>

        <section className={styles.about}>
          <h1 className={styles.title}>
              Simon <br/> Wilmots
          </h1>

          <div className={styles.info}>
            <OutlinedArrow width="4rem" height="4rem"/>
            <StatusText text={"Student"}/>
          </div>
          
        </section>
        

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        
      </main>
    </div>
  )
}
